# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
